### ISSUE TITLE
Find solution for who is going to stuff bags

### ISSUE THREAD

**Issue by DinisCruz** [OWASP/owasp-summits#1054]
If this is going to be quite a bit of work (and there are other similar 'repetitive and easy to delegate' tasks), then let's look at getting a freelancer on site on Sunday and/or Monday

![image](https://user-images.githubusercontent.com/656739/26927564-54627f68-4c4a-11e7-90eb-4c98a8fc6ece.png)

**Comment by jemmads** [comment]
Jemma B has agreed to this task and will be onsite from lunch time Sunday

**Comment by jemmads** [comment]
Jemma B has agreed to this task and will be onsite from lunch time Wednesday

**Comment by DinisCruz** [comment]
more info
![image](https://user-images.githubusercontent.com/656739/26928066-806ece8e-4c4c-11e7-919f-eb12a7daedb3.png)

**Comment by jemmads** [comment]
Jemma B has agreed to this task and will be onsite from lunch time Wednesday

**Comment by jemmads** [comment]
jemmads [1:23 PM] 
I have a price back from a supplier:

[1:23] 
I have put together the quotation below for a Guaranteed Despatch Date of 09/06/2017, with an expected Delivery Date of 10/06/2017.
In order to achieve this delivery date, you will need to confirm the order by completing and returning the details requested in my follow up email no later than 1PM today.
Once your order is processed, a proof will be sent via email for your approval prior to printing. This will need to be approved as soon as it arrives with you.
If you have any questions please reply to this email, or give me a ring on 01938 530 050
Kind regards
Annie
Quote ID: 358960

Product: White canvas 8oz Carrier 36x39cm Long Handles (LH-3639-8VWT)
Quantity: 150
Design Info: One design on one side
Estimated Despatch Time: 3-5 Working days from digital proof approval
Side One FULL COLOUR
Price Each: 3.99 GBP
GDD Charge: 80.00 GBP
Carriage: 33.65 GBP SATURDAY DELIVERY
Total Price exc. VAT:712.15 GBP + VAT

[1:23] 
Although the quote has just come through so don't worry too much about the 1pm deadline

[1:24] 
Payment needs to be made asap

[1:24] 
Can this be approved?

**Comment by DinisCruz** [comment]
nice one, this is the way to do it, always put all info on a GitHub issue

**Comment by jemmads** [comment]
ARtwork supplied to printer at this point is attached
[sponsor logos copy.pdf](https://github.com/OWASP/owasp-summit-2017/files/1060960/sponsor.logos.copy.pdf)

**Comment by jemmads** [comment]
![bag graphics v1](https://user-images.githubusercontent.com/29257887/26929643-51f36802-4c52-11e7-89f5-0d1de1e4fae9.png)

**Comment by jemmads** [comment]
Bags due to arrive on site today. @JemmaButtle and I will stuff as soon as swag and bags are here. Any volunteers welcome

**Comment by fzipi** [comment]
We should close this.
