### ISSUE TITLE
Create logo for public social accounts

### ISSUE THREAD

**Issue by FrancoisRaynaud** [OWASP/owasp-summits#12]

**Comment by FrancoisRaynaud** [comment]
Lisa is working on the logo

**Comment by FrancoisRaynaud** [comment]
![owasp-devseccon](https://cloud.githubusercontent.com/assets/23117184/19836779/fae4dd46-9ea2-11e6-91db-8cb72ae3ad30.JPG)
comments?

**Comment by DinisCruz** [comment]
I really liked the previous Summit logo

![image](https://cloud.githubusercontent.com/assets/656739/19837423/29e017ba-9eb1-11e6-98a2-5107d472281a.png)

See https://www.owasp.org/index.php/Summit_2011_Logo_Explained

But I see what she is trying to do (merging both logos)

**Comment by FrancoisRaynaud** [comment]
I do like it as well although the previous logo is tied to the location (Portugal) and the compass idea as well.
Therefore we need a set of requirements for the logo:
- do both OWASP and DevSecCon needs to be represented?
- should the location be represented?
- being a summit to renew the 2011 vibe, should it reflect the "start again" aspect?

**Comment by DinisCruz** [comment]
> do both OWASP and DevSecCon needs to be represented?

I think it would be good, but I would but it as a deal breaker. If we have a logo that we all go _"YES that's it!"_  but it doesn't have one of both logos, we should go with it

> should the location be represented?

It would be an good thing to do it. Btw the more I think about it, the more I'm convinced that It needs to be close to London, since there are a lot of key senior players that we need to participate in the Summit that will only be able to pop in for a couple hours if it is physically close to where they are. And there are a LOT of key players in London

> being a summit to renew the 2011 vibe, should it reflect the "start again" aspect?

Yeah I like that, this does have a 'reboot' feel to it
