### ISSUE TITLE
Create page with list of Participant's page's status

### ISSUE THREAD

**Issue by DinisCruz** [OWASP/owasp-summits#183]
so that we can easily see which Participants have a good page (i.e with content) and which ones need more info

**Comment by NikitaOwasp** [comment]
Hi @DinisCruz, how exactly do you want to go about this? I could create an excel sheet with names of all participants and add rows with what's missing on their page (like photo, bio, linkedin, twitter accounts, etc.) 
OR 
Since I'm aligning the pages, I find that almost everyone needs to update their page. I think it would be best to tell them via slack (is there a group where I can reach out to all participants?) or email to tell them to update their pages. And, then I could work on the alignment task as well once all info is there on the pages.

Thanks,

**Comment by DinisCruz** [comment]
This is done

http://owaspsummit.org/pages/for-editors/participants/funding.html

![image](https://cloud.githubusercontent.com/assets/656739/25563915/b83451f8-2d9e-11e7-8f25-1451d2f12016.png)

Now we need to act on the info in there
