### ISSUE TITLE
prepare registrations / name badges

### ISSUE THREAD

**Issue by SebaDele** [OWASP/owasp-summits#909]

**Comment by jemmads** [comment]
Has any action been taken on this at all?

**Comment by jemmads** [comment]
Graphics to be discussed on call 8/6
Jemma DS to create artwork
Inserts and pouches to be ordered from Amazon and printed on site

**Comment by jemmads** [comment]
Graphic completed and approved on slack
[24 hour badge template.docx](https://github.com/OWASP/owasp-summit-2017/files/1065709/24.hour.badge.template.docx)
[day badge template.docx](https://github.com/OWASP/owasp-summit-2017/files/1065710/day.badge.template.docx)

Trip to supplier needs to be arranged for Saturday so that these can be created in good time
